/*
 * MeasureToolListener.java
 *
 * Created on April 22, 2005, 2:47 PM
 */

package edu.oregonstate.cartography.map;

import edu.oregonstate.cartography.simplefeature.AbstractSimpleFeatureMapComponent;

/**
 * MeasureToolListener - a listener for events generated by a MeasureTool.
 * @author Bernhard Jenny, Institute of Cartography, ETH Zurich.
 */
public interface MeasureToolListener {
    
    /**
     * The measure tool has computed a new distance. This is called while the
     * user drags the mouse.
     * @param distance The new distance.
     * @param angle
     * @param mapComponent
     */
    void distanceChanged(double distance, double angle, AbstractSimpleFeatureMapComponent mapComponent);
    
    /**
     * The measure tool has computed a new distance. This is called when the user
     * releases the mouse.
     * @param distance The new distance.
     * @param angle
     * @param mapComponent
     */
    void newDistance(double distance, double angle, AbstractSimpleFeatureMapComponent mapComponent);
    
    
    /**
     * The mouse has been released, the line is therefore not visible anymore
     * in the map.
     */
    void clearDistance();
}
